version: '3.8'

services:
  backend:
    build: ./backend/student-card-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - panafrican-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - panafrican-net

networks:
  panafrican-net:
    driver: bridge
